Repository PKNU-CERT-IS/FE, pull requests merged in 2025-07, with the labels that each got.

#6 Feat: Study Page 구현 #5
  package-lock.json
  package.json
  public/icons/add.svg
  public/icons/alert-triangle.svg
  public/icons/angle.svg
  public/icons/blog.svg
  public/icons/bug.svg
  public/icons/calendar-gray.svg
  public/icons/chat.svg
  public/icons/download-gray.svg
  public/icons/eye.svg
  public/icons/file.svg
  public/icons/globe-gray.svg
  public/icons/globe-red.svg
  public/icons/info.svg
  public/icons/location.svg
  public/icons/lock.svg
  public/icons/logo-white.svg
  public/icons/logo.svg
  public/icons/next.svg
  public/icons/pdf.svg
  public/icons/people.svg
  public/icons/plus.svg
  public/icons/schedule.svg
  public/icons/search.svg
  public/icons/server.svg
  public/icons/shield.svg
  public/icons/study.svg
  public/icons/terminal.svg
  public/icons/thumbs-up.svg
  public/icons/thunder.svg
  public/icons/time.svg
  public/icons/vercel.svg
  public/icons/window.svg
  public/icons/zip.svg
  src/actions/study/StudyDownloadFileServerAction.tsx
  src/actions/study/StudyJoinServerAction.tsx
  src/actions/study/StudySearchServerAction.tsx
  src/app/globals.css
  src/app/page.tsx
  src/app/study/page.tsx
  src/components/miniCalendar.tsx
  src/components/nav/bugReport.tsx
  src/components/study/CCStudyDateInfo.tsx
  src/components/study/CCStudyFilter.tsx
  src/components/study/CCStudyPagination.tsx
  src/components/study/SCStudyContent.tsx
  src/components/study/SCStudyDescription.tsx
  src/components/study/SCStudySearchResultNotFound.tsx
  src/components/study/SCStudySkeleton.tsx
  src/layouts/footer.tsx
  src/layouts/navigationBar.tsx
  src/types/global.d.ts
  src/types/study.ts
  src/utils/study/studyHelper.tsx
  tsconfig.json
Labels: feat, build, chore

#17 Feat: Login, SignUp Page 구현 #15
  public/icons/lock.svg
  public/icons/profile.svg
  public/icons/shield.svg
  src/actions/auth/LoginServerAction.tsx
  src/actions/auth/SignUpServerAction.tsx
  src/app/board/layout.tsx
  src/app/globals.css
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/profile/layout.tsx
  src/app/signup/page.tsx
  src/components/auth/SCAuthBackGround.tsx
  src/components/auth/SCAuthSwitchButton.tsx
  src/components/auth/SCAuthTitle.tsx
  src/components/auth/login/CCLoginForm.tsx
  src/components/auth/login/SCLoginContainer.tsx
  src/components/auth/signup/CCSignUpForm.tsx
  src/components/auth/signup/SCSignUpContainer.tsx
  src/components/board/SCBoardCardList.tsx
  src/components/nav/bugReport.tsx
  src/components/nav/loginButton.tsx
  src/components/ui/defaultButton.tsx
  src/hooks/useAuth.tsx
  src/layouts/navigationBar.tsx
  src/types/login.ts
Labels: feat

#28 Fix: 새 페이지 작성 페이지 애니메이션 효과 문제
  public/icons/shield.svg
  src/app/page.tsx
  src/components/write/CCNewPageModal.tsx
Labels: fix

#32 Feat, Refactor: NavBar 햄버거 메뉴 구현, CSS 모듈화 및 디자인 리팩토링 #19
  package-lock.json
  package.json
  public/icons/thunder.svg
  src/app/blog/page.tsx
  src/app/board/[id]/page.tsx
  src/app/board/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/app/profile/page.tsx
  src/app/project/[id]/page.tsx
  src/app/project/page.tsx
  src/app/study/[id]/page.tsx
  src/components/auth/SCAuthSwitchButton.tsx
  src/components/auth/login/CCLoginForm.tsx
  src/components/auth/signup/CCSignUpForm.tsx
  src/components/blog/CCBlogCategoryFilter.tsx
  src/components/blog/CCBlogPagination.tsx
  src/components/blog/CCBlogSearchBar.tsx
  src/components/board/CCBoardCategory.tsx
  src/components/board/CCBoardSearchBar.tsx
  src/components/board/SCBoardCard.tsx
  src/components/board/SCBoardPagination.tsx
  src/components/detail/CCBookmarkButton.tsx
  src/components/detail/CCKebabMenu.tsx
  src/components/members/CCMembersDropdown.tsx
  src/components/members/CCMembersSearchBar.tsx
  src/components/members/SCMembersCard.tsx
  src/components/miniCalendar.tsx
  src/components/nav/bugReport.tsx
  src/components/nav/hamburgerMenu.tsx
  src/components/nav/loginButton.tsx
  src/components/nav/navBarItems.tsx
  src/components/profile/CCEditProfileCard.tsx
  src/components/profile/CCProfileModal.tsx
  src/components/profile/CCProfilePagination.tsx
  src/components/profile/CCTabBar.tsx
  src/components/profile/SCBlogList.tsx
  src/components/profile/SCPenaltyStatus.tsx
  src/components/profile/SCProfileContent.tsx
  src/components/profile/SCStudyList.tsx
  src/components/profile/SCTodaySchedule.tsx
  src/components/project/CCProjectCategory.tsx
  src/components/project/CCProjectPagination.tsx
  src/components/project/SCProjectContent.tsx
  src/components/schedule/CCAddScheduleCard.tsx
  src/components/schedule/SCScheduleList.tsx
  src/components/schedule/calendar.tsx
  src/components/schedule/scheduleFormModal.tsx
  src/components/sectionBadge.tsx
  src/components/study/CCMeetingMinutes.tsx
  src/components/study/CCStudyFilter.tsx
  src/components/study/CCStudyPagination.tsx
  src/components/study/SCStudyContent.tsx
  src/components/study/SCStudySearchResultNotFound.tsx
  src/components/ui/defaultButton.tsx
  src/layouts/navigationBar.tsx
Labels: feat, refactor

#29 Feat,Refactor: 프로젝트 새글 작성 및 수정 폼 구현
  src/app/favicon.ico
  src/app/profile/page.tsx
  src/app/project/[id]/edit/page.tsx
  src/app/project/[id]/page.tsx
  src/app/project/write/page.tsx
  src/app/study/page.tsx
  src/components/study/CCStudyDateInfo.tsx
  src/components/study/SCStudyContent.tsx
  src/components/write/CCEditForm.tsx
  src/components/write/CCWriteForm.tsx
  src/types/newPageForm.ts
  src/utils/blogUtils.ts
  src/utils/newPageFormUtils.ts
  src/utils/studyHelper.tsx
Labels: feat, refactor

#35 Fix: 폴더구조 변환으로 인한 모듈 불러오기 오류 해결
  src/app/blog/page.tsx
  src/components/study/CCStudyPagination.tsx
  src/utils/newPageFormUtils.ts
Labels: fix
