Repository PKNU-CERT-IS/FE, pull requests merged in 2025-09, with the labels that each got.

#63 Feat: Meatdata 작성#62
  src/app/(main)/blog/[id]/page.tsx
  src/app/(main)/blog/page.tsx
  src/app/(main)/board/[id]/page.tsx
  src/app/(main)/board/page.tsx
  src/app/(main)/members/page.tsx
  src/app/(main)/page.tsx
  src/app/(main)/profile/page.tsx
  src/app/(main)/project/[id]/page.tsx
  src/app/(main)/project/page.tsx
  src/app/(main)/schedule/page.tsx
  src/app/(main)/study/[id]/page.tsx
  src/app/(main)/study/page.tsx
  src/components/profile/CCProfileEditModal.tsx
  src/components/schedule/CCScheduleFormModal.tsx
  src/middleware.ts
Labels: feat

#71 Auth 도메인 api 작업
  package-lock.json
  package.json
  src/actions/auth/LoginServerAction.tsx
  src/actions/auth/LogoutServerAction.tsx
  src/actions/auth/SignUpServerAction.tsx
  src/app/api/profile/SCprofileApi.ts
  src/app/api/schedule/route.ts
  src/components/admin/login/CCAdminLoginForm.tsx
  src/components/auth/login/CCLoginForm.tsx
  src/components/auth/signup/CCSignUpForm.tsx
  src/components/nav/loginButton.tsx
  src/components/profile/SCProfileCard.tsx
  src/lib/clientIntercept.ts
  src/lib/serverIntercept.ts
  src/store/authStore.ts
  src/utils/transformRequestValue.ts
Labels: feat

#86 Feat, Fix: Admin Study, Project 필터 수정 + Home Study, Project API 작업#85
  src/app/(admin)/admin/layout.tsx
  src/app/(admin)/admin/study/[id]/studyDetailPage.tsx
  src/app/(admin)/admin/study/page.tsx
  src/app/api/project/SCProjectApi.tsx
  src/app/api/study/SCStudyApi.tsx
  src/components/admin/home/SCActivityDashBoard.tsx
  src/components/admin/home/SCTotalDashBoard.tsx
  src/components/admin/study/SCProjectContentList.tsx
  src/components/admin/study/SCStudyContentList.tsx
  src/components/project/CCProjectFilter.tsx
  src/components/project/CCProjectPagination.tsx
  src/components/study/CCStudyFilter.tsx
  src/components/study/SCStudyContent.tsx
  src/components/ui/CCParticipantActionButtons.tsx
  src/components/write/CCWriteForm.tsx
  src/types/project.ts
  src/types/study.ts
  src/utils/studyHelper.tsx
Labels: feat, fix

#88 Fix: sentry 에러로 인한 비활성화
  next.config.ts
  src/app/(admin)/admin/study/page.tsx
  src/components/project/CCProjectFilter.tsx
Labels: fix

#98 Refactor: 전화번호 포맷팅 및 전공 ENUM 관리
  src/actions/auth/LogoutServerAction.tsx
  src/components/auth/signup/CCSignUpForm.tsx
  src/components/profile/CCProfileEditModal.tsx
  src/components/profile/SCProfileContent.tsx
  src/components/ui/CCDefaultSuspnenseComponent.tsx
  src/lib/clientIntercept.ts
  src/lib/serverIntercept.ts
  src/types/major.ts
  src/utils/formEditUtils.ts
Labels: refactor
